apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: geek-auth-mongo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: geek-auth-mongo
    spec:
      containers:
        - name: geek-auth-mongo
          image: mongo
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 27017
---

apiVersion: v1
kind: Service
metadata:
  name: geek-auth-mongo
spec:
  ports:
    - port: 27017
  selector:
    app: geek-auth-mongo
---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: geek-user-mongo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: geek-user-mongo
    spec:
      containers:
        - name: geek-user-mongo
          image: mongo
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 27017
---

apiVersion: v1
kind: Service
metadata:
  name: geek-user-mongo
spec:
  ports:
    - port: 27017
  selector:
    app: geek-user-mongo

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: geek-task-mysql
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: geek-task-mysql
    spec:
      containers:
        - name: geek-task-mysql
          image: mysql:5.6.35
          imagePullPolicy: IfNotPresent
          env:
            # Use secret in real usage
            - name: MYSQL_ROOT_PASSWORD
              value: root
          ports:
            - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: geek-task-mysql
spec:
  ports:
    - port: 3306
  selector:
    app: geek-task-mysql