version: '3'
services:

  geek-message-service:
    build: geek-message-service
    image: 10.141.211.160:5000/geek/geek-message-service
    restart: always
    ports:
#      web port socket port
      - 18009:18009
      - 18008:18008
    networks:
      - geek-network

networks:
  geek-network:
    driver: bridge
