apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: geek-ui-dashboard
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: geek-ui-dashboard
    spec:
      containers:
        - name: geek-ui-dashboard
          image: 10.141.211.160:5000/geek/geek-ui-dashboard
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              cpu: 500m
              memory: 500Mi

---

apiVersion: v1
kind: Service
metadata:
  name: geek-ui-dashboard
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      nodePort: 32677
  selector:
    app: geek-ui-dashboard