server:
  port: 18000
spring:
  application:
    name: geek-auth-service
  data:
    mongodb:
      host: geek-auth-mongo
      database: geek-auth
      port: 27017
#  data:
#    mongodb:
#      host: 10.141.211.161
#      database: geek-auth
#      port: 30008
