version: '3'
services:

  geek-task-mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    command: [
      --character-set-server=utf8mb4,
      --collation-server=utf8mb4_unicode_ci
    ]
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: geek
    networks:
      - test-mysql1-network

networks:
  test-mysql1-network:
    driver: bridge