server:
  port: 18001
spring:
  application:
    name: geek-user-service
  data:
    mongodb:
      host: geek-user-mongo
      database: geek-user
      port: 27017
#  data:
#    mongodb:
#      host: 10.141.211.161
#      database: geek-user
#      port: 30007