server:
  port: 18002
spring:
  application:
    name: geek-task-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://geek-task-mysql:3306/geek_db?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
  jooq:
    sql-dialect: org.hibernate.dialect.MySQL5Dialect

#  spring.jpa.database-platform = #要运行的目标数据库的名称，默认情况下自动检测。可以使用“数据库”枚举来设置
# JOOQ (JooqAutoConfiguration)
# spring.jooq.sql-dialect=  # 与配置的数据源通信时使用的SQLDialect JOOQ。 例如`POSTGRES`